import { StyleSheet } from 'react-native';

import { colors } from '../../../constants/colors';

export const roomStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flexGrow: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 20,
    paddingTop: 44,
    paddingBottom: 20,
    gap: 14,
  },
  header: {
    gap: 8,
    paddingTop: 8,
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  badge: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  title: {
    color: colors.text,
    fontSize: 28,
    lineHeight: 33,
    fontWeight: '900',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  codeChip: {
    backgroundColor: colors.surfaceRaised,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  codeChipLabel: {
    color: colors.textSoft,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  codeChipValue: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  subtitle: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  inviteCard: {
    backgroundColor: colors.accentMuted,
    borderRadius: 22,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  stageCard: {
    backgroundColor: colors.accentMuted,
    borderRadius: 24,
    padding: 20,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  adminCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  summaryCard: {
    backgroundColor: colors.accentMuted,
    borderRadius: 24,
    padding: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  closedBanner: {
    backgroundColor: colors.dangerMuted,
    borderRadius: 20,
    padding: 16,
    gap: 6,
    borderWidth: 1,
    borderColor: '#6E2638',
  },
  closedTitle: {
    color: colors.danger,
    fontSize: 20,
    fontWeight: '900',
  },
  closedText: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  cardLabel: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cardValue: {
    color: colors.text,
    fontSize: 19,
    fontWeight: '800',
    marginBottom: 4,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    flexShrink: 1,
  },
  counter: {
    minWidth: 32,
    textAlign: 'center',
    color: colors.background,
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 14,
    fontWeight: '900',
    overflow: 'hidden',
  },
  inviteCode: {
    color: colors.text,
    fontSize: 34,
    lineHeight: 40,
    letterSpacing: 6,
    fontWeight: '900',
  },
  inviteText: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  stageName: {
    color: colors.text,
    fontSize: 34,
    lineHeight: 39,
    fontWeight: '900',
  },
  stageHint: {
    color: colors.primary,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '800',
  },
  heroEyebrow: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  freeStageBox: {
    gap: 4,
  },
  participationText: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  statePill: {
    color: colors.primary,
    backgroundColor: colors.primaryMuted,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
  },
  buttonGroup: {
    gap: 10,
  },
  inlineButtonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  loadingText: {
    color: colors.textMuted,
    fontSize: 14,
    flexShrink: 1,
  },
  errorText: {
    color: colors.danger,
    fontSize: 14,
    lineHeight: 20,
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  memberItem: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    gap: 10,
  },
  memberInfo: {
    gap: 3,
    flex: 1,
  },
  memberActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  memberName: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  memberRole: {
    color: colors.textSoft,
    fontSize: 13,
    marginTop: 3,
  },
  youBadge: {
    color: colors.background,
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
  },
  manualBadge: {
    color: colors.text,
    backgroundColor: colors.accentMuted,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
  },
  queueItem: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  queuePosition: {
    width: 34,
    height: 34,
    borderRadius: 999,
    backgroundColor: colors.primary,
    color: colors.background,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 16,
    fontWeight: '900',
    overflow: 'hidden',
  },
  queueInfo: {
    flex: 1,
  },
  queueAdminActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 6,
    maxWidth: 132,
  },
  manualQueueBox: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    gap: 10,
  },
  manualQueueInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    color: colors.text,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    fontWeight: '700',
  },
  eventItem: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    gap: 4,
  },
  eventTime: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: '800',
  },
  eventText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryBox: {
    flexGrow: 1,
    flexBasis: '45%',
    backgroundColor: colors.surfaceRaised,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  scoreHero: {
    backgroundColor: colors.primaryMuted,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
  },
  scoreNumber: {
    color: colors.primary,
    fontSize: 46,
    lineHeight: 52,
    fontWeight: '900',
  },
  scoreLabel: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  summaryNumber: {
    color: colors.primary,
    fontSize: 30,
    fontWeight: '900',
  },
  summaryLabel: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },
  highlightBox: {
    backgroundColor: colors.primaryMuted,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  highlightLabel: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  highlightName: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '900',
    marginTop: 4,
  },
  rankingBox: {
    gap: 10,
  },
  rankingItem: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  rankingPosition: {
    width: 34,
    height: 34,
    borderRadius: 999,
    backgroundColor: colors.primary,
    color: colors.background,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 16,
    fontWeight: '900',
    overflow: 'hidden',
  },
  rankingInfo: {
    flex: 1,
  },
  adminText: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 19,
  },
  ownerBadge: {
    color: colors.background,
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
  },
  ownerActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 10,
  },
  ownerHint: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: '800',
  },
  footerActions: {
    gap: 10,
    marginTop: 4,
    marginBottom: 24,
  },
});
